name: Prettier Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check .
