name: '[STAGING] Build and Deploy'
on:
  push:
    branches:
      - staging

env:
  NODE_VERSION: 16

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn deploy
