name: '[STAGING] Build and Deploy'
on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  NODE_VERSION: 16

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and Build 🔧
        run: yarn install

      - name: Build and deploy
        run: yarn deploy
