
name: Test Modifiers

on:
  workflow_dispatch:
  
env:
  NODE_VERSION: 16

jobs:
  testModifiers:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: yarn testModifiers
